# Generated by Django 3.2.8 on 2024-05-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0021_auto_20240513_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieritem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='supplieritem',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='suppliers',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='SupplierItem',
        ),
    ]
