# Generated by Django 3.2.8 on 2024-05-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0022_auto_20240516_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item',
            new_name='id',
        ),
    ]
