# Generated by Django 5.0.6 on 2024-05-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierItem',
            new_name='SuppliedItem',
        ),
    ]
