# Generated by Django 5.0.6 on 2024-05-15 11:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_reference', models.CharField(help_text='The purchase order reference number', max_length=40)),
                ('ordered_by', models.CharField(help_text='The person or department that the order is for', max_length=30)),
                ('date_enquired', models.DateField(blank=True, null=True)),
                ('date_order_placed', models.DateField(default=datetime.date.today)),
                ('date_expected_delivery', models.DateField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('performance_metric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_order', to='purchase_tracker.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_tracker.order')),
            ],
            options={
                'unique_together': {('item', 'order')},
            },
        ),
        migrations.CreateModel(
            name='DeliveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delivered', models.IntegerField()),
                ('delivery_date', models.DateField(default=datetime.date.today)),
                ('ordered_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='purchase_tracker.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_orders', to='purchase_tracker.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_page', models.URLField(blank=True, null=True)),
                ('expected_lead_time', models.DurationField(blank=True, null=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_tracker.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_tracker.supplier')),
            ],
            options={
                'unique_together': {('item', 'supplier')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='suppliers',
            field=models.ManyToManyField(related_name='supplied_items', through='purchase_tracker.SupplierItem', to='purchase_tracker.supplier'),
        ),
    ]
